
POST http://localhost:5000/notify/login HTTP/1.1
content-type: application/json

{
    "title": "Log In!!!",
    "message": "Remember to sign in"
}

###
POST http://localhost:5000/notify/logout HTTP/1.1
content-type: application/json

{
    "title": "Log out!!!",
    "message": "Remember to log out"
}

###
GET http://localhost:5000/

###
GET http://localhost:5000/health

